version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: cruxclimb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: cruxclimb
      POSTGRES_PASSWORD: cruxclimb123
      POSTGRES_DB: cruxclimb_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cruxclimb']
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:latest
    container_name: cruxclimb-localstack
    restart: unless-stopped
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSISTENCE=0
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  localstack_data:
