import {ICountryInfo} from './PhoneInput.types';

export const COUNTRIES: ICountryInfo[] = [
  {cca2: 'AR', callingCode: '54', flag: '🇦🇷', name: 'Argentina'},
  {cca2: 'MX', callingCode: '52', flag: '🇲🇽', name: 'México'},
  {cca2: 'ES', callingCode: '34', flag: '🇪🇸', name: 'España'},
  {cca2: 'US', callingCode: '1', flag: '🇺🇸', name: 'Estados Unidos'},
  {cca2: 'CL', callingCode: '56', flag: '🇨🇱', name: 'Chile'},
  {cca2: 'CO', callingCode: '57', flag: '🇨🇴', name: 'Colombia'},
  {cca2: 'PE', callingCode: '51', flag: '🇵🇪', name: 'Perú'},
  {cca2: 'VE', callingCode: '58', flag: '🇻🇪', name: 'Venezuela'},
  {cca2: 'UY', callingCode: '598', flag: '🇺🇾', name: 'Uruguay'},
  {cca2: 'PY', callingCode: '595', flag: '🇵🇾', name: 'Paraguay'},
  {cca2: 'BO', callingCode: '591', flag: '🇧🇴', name: 'Bolivia'},
  {cca2: 'EC', callingCode: '593', flag: '🇪🇨', name: 'Ecuador'},
  {cca2: 'BR', callingCode: '55', flag: '🇧🇷', name: 'Brasil'},
  {cca2: 'CR', callingCode: '506', flag: '🇨🇷', name: 'Costa Rica'},
  {cca2: 'PA', callingCode: '507', flag: '🇵🇦', name: 'Panamá'},
  {cca2: 'GT', callingCode: '502', flag: '🇬🇹', name: 'Guatemala'},
  {cca2: 'HN', callingCode: '504', flag: '🇭🇳', name: 'Honduras'},
  {cca2: 'SV', callingCode: '503', flag: '🇸🇻', name: 'El Salvador'},
  {cca2: 'NI', callingCode: '505', flag: '🇳🇮', name: 'Nicaragua'},
  {cca2: 'CU', callingCode: '53', flag: '🇨🇺', name: 'Cuba'},
  {cca2: 'DO', callingCode: '1', flag: '🇩🇴', name: 'República Dominicana'},
  {cca2: 'PR', callingCode: '1', flag: '🇵🇷', name: 'Puerto Rico'},
  {cca2: 'CA', callingCode: '1', flag: '🇨🇦', name: 'Canadá'},
  {cca2: 'GB', callingCode: '44', flag: '🇬🇧', name: 'Reino Unido'},
  {cca2: 'FR', callingCode: '33', flag: '🇫🇷', name: 'Francia'},
  {cca2: 'DE', callingCode: '49', flag: '🇩🇪', name: 'Alemania'},
  {cca2: 'IT', callingCode: '39', flag: '🇮🇹', name: 'Italia'},
  {cca2: 'PT', callingCode: '351', flag: '🇵🇹', name: 'Portugal'},
  {cca2: 'NL', callingCode: '31', flag: '🇳🇱', name: 'Países Bajos'},
  {cca2: 'BE', callingCode: '32', flag: '🇧🇪', name: 'Bélgica'},
  {cca2: 'CH', callingCode: '41', flag: '🇨🇭', name: 'Suiza'},
  {cca2: 'AT', callingCode: '43', flag: '🇦🇹', name: 'Austria'},
  {cca2: 'SE', callingCode: '46', flag: '🇸🇪', name: 'Suecia'},
  {cca2: 'NO', callingCode: '47', flag: '🇳🇴', name: 'Noruega'},
  {cca2: 'DK', callingCode: '45', flag: '🇩🇰', name: 'Dinamarca'},
  {cca2: 'FI', callingCode: '358', flag: '🇫🇮', name: 'Finlandia'},
  {cca2: 'PL', callingCode: '48', flag: '🇵🇱', name: 'Polonia'},
  {cca2: 'RU', callingCode: '7', flag: '🇷🇺', name: 'Rusia'},
  {cca2: 'CN', callingCode: '86', flag: '🇨🇳', name: 'China'},
  {cca2: 'JP', callingCode: '81', flag: '🇯🇵', name: 'Japón'},
  {cca2: 'KR', callingCode: '82', flag: '🇰🇷', name: 'Corea del Sur'},
  {cca2: 'IN', callingCode: '91', flag: '🇮🇳', name: 'India'},
  {cca2: 'AU', callingCode: '61', flag: '🇦🇺', name: 'Australia'},
  {cca2: 'NZ', callingCode: '64', flag: '🇳🇿', name: 'Nueva Zelanda'},
  {cca2: 'ZA', callingCode: '27', flag: '🇿🇦', name: 'Sudáfrica'},
  {cca2: 'EG', callingCode: '20', flag: '🇪🇬', name: 'Egipto'},
  {cca2: 'SA', callingCode: '966', flag: '🇸🇦', name: 'Arabia Saudita'},
  {cca2: 'AE', callingCode: '971', flag: '🇦🇪', name: 'Emiratos Árabes Unidos'},
  {cca2: 'IL', callingCode: '972', flag: '🇮🇱', name: 'Israel'},
  {cca2: 'TR', callingCode: '90', flag: '🇹🇷', name: 'Turquía'},
];
